name: "Compliance"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  semantics:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  compliance-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: mtfoley/pr-compliance-action@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          watch-files: >
            package.json
            npm-shrinkwrap.json

  welcome:
    runs-on: ubuntu-latest
    needs: semantics
    if: github.event.action == 'opened'

    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |-
            Congrats on making your first Pull Request and thanks for taking the time to improve Open Sauced! â¤ï¸! ğŸ‰ğŸ•
            Say hello by joining the conversation in our [Discord](https://discord.gg/U2peSNf23P)
