name: Maintenance

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  workflow_call:

jobs:
  maintenance:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "ğŸ—‘ï¸ Remove old artifacts"
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '10 days'
          skip-recent: 5
          skip-tags: false
