on: pull_request
 branches:
      - master
name: automerge pull requests on updates
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: automerge
      uses: pascalgn/automerge-action@33f73f0a562129c7e96123e98af20d4378f1fa3b
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
